[package]
name = "screen_capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1.4.5", features = ["no-pango", "no-images"] }
screenshots = { version = "0.6.0" }