[package]
name = "screen_capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27.5"
wgpu = "0.14.0"
gfx = "0.18.2"

#piston_window = "0.127.0"

fltk = { version = "1.4.5", features = ["no-pango", "no-images"] }